import { Metadata } from "next";

export const noticiasMetadata: Metadata = {
  keywords: [
    "Ghost",
    "noticias",
    "news",
    "rock",
    "theatrical rock",
    "Tobias Forge",
    "actualidad",
    "últimas noticias",
    "tour Ghost",
    "conciertos Ghost",
    "pop metal",
    "Impera Tour",
    "gira Ghost 2024",
    "Ghost news",
    "Ghost Argentina presencia",
    "Ghost fanbase Argentina",
    "Ghost Latinoamérica alcance",
    "Ghost Spanish-speaking fans",
    "Ghost en español",
    "Ghost traductor lyrics",
    "Ghost noticias en español",
    "Ghost entrevistas españolas",
    "Ghost podcasts español",
    "Ghost radio Argentina",
    "Ghost band",
    "Ghost Swedish band",
    "Ghost theatrical rock",
    "Ghost Tobias Forge",
    "Ghost Papa Emeritus",
    "Ghost Nameless Ghouls",
    "Ghost Cirice",
    "Ghost Mary on a Cross",
    "Ghost tour dates",
    "Ghost new album",
    "Ghost latest news",
    "Ghost discography list",
    "Ghost album rankings",
    "Ghost best songs",
    "Ghost unplugged",
    "Ghost covers",
    "Ghost tributes",
    "banda Ghost",
    "Ghost banda sueca",
    "Ghost music",
    "Ghost band members",
    "Ghost official",
    "Ghost real members",
    "who is Ghost",
    "identidad Ghost",
    "Papa Emeritus identity",
    "Tobias Forge Ghost",
    "Ghost founder",
    "Ghost mastermind",
    "Ghost fan site",
    "Ghost Argentina fans",
    "Ghost comunidad",
    "Ghost fandom",
    "Ghost noticias actualidad",
    "últimas noticias Ghost",
    "Ghost breaking news",
    "Ghost anuncios",
    "Ghost discografía completa",
    "Ghost letras",
    "Ghost lyrics",
    "Ghost canciones",
    "Ghost entrevistas",
    "Ghost noticias",
    "Ghost streaming",
    "Ghost Spotify",
    "Ghost Apple Music",
    "Ghost YouTube",
    "Ghost videos oficiales",
    "Ghost documentales",
    "Ghost behind the scenes"
  ].join(", "),
  authors: [{ name: "Ghost Argentina" }],
  category: "Music",
  verification: {
    google: "google-site-verification-code", // Reemplazar con tu código real
  },
};
