import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Entrevistas | Ghost",
  description: "Colección completa de entrevistas a los miembros de Ghost a lo largo de su historia. Desde los inicios en 2006 hasta la actualidad, accede a conversaciones exclusivas, declaraciones históricas y momentos únicos de Tobias Forge, Papa Emeritus y todos los integrantes de la banda.",
  keywords: [
    "Ghost",
    "entrevistas",
    "interviews",
    "theatrical rock",
    "pop metal",
    "Tobias Forge",
    "Papa Emeritus",
    "Nameless Ghouls",
    "Ghost band members",
    "Ghost interviews",
    "Ghost declaraciones",
    "Ghost statements",
    "conversaciones Ghost",
    "Ghost conversations",
    "band interviews",
    "metal interviews",
    "Ghost Argentina presencia",
    "Ghost fanbase Argentina",
    "Ghost Latinoamérica alcance",
    "Ghost Spanish-speaking fans",
    "Ghost en español",
    "Ghost traductor lyrics",
    "Ghost noticias en español",
    "Ghost entrevistas españolas",
    "Ghost podcasts español",
    "Ghost radio Argentina",
    "Ghost band",
    "Ghost Swedish band",
    "Ghost theatrical rock",
    "Ghost Tobias Forge",
    "Ghost Papa Emeritus",
    "Ghost Nameless Ghouls",
    "Ghost Cirice",
    "Ghost Mary on a Cross",
    "Ghost tour dates",
    "Ghost new album",
    "Ghost latest news",
    "Ghost discography list",
    "Ghost album rankings",
    "Ghost best songs",
    "Ghost unplugged",
    "Ghost covers",
    "Ghost tributes",
    "banda Ghost",
    "Ghost banda sueca",
    "Ghost music",
    "Ghost official",
    "Ghost real members",
    "who is Ghost",
    "identidad Ghost",
    "Papa Emeritus identity",
    "Tobias Forge Ghost",
    "Ghost founder",
    "Ghost mastermind",
  ],
  openGraph: {
    title: "Entrevistas | Ghost",
    description: "Colección completa de entrevistas a los miembros de Ghost a lo largo de su historia.",
    url: "/entrevistas",
    siteName: "Ghost Fan Site",
    type: "website",
    images: [
      {
        url: "/images/banners/interviews.png",
        width: 1200,
        height: 630,
        alt: "Entrevistas de Ghost - Colección completa",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Entrevistas | Ghost",
    description: "Colección completa de entrevistas a los miembros de Ghost a lo largo de su historia.",
    images: ["/images/banners/interviews.png"],
    creator: "@GhostFanSite",
  },
  alternates: {
    canonical: "/entrevistas",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};